remote_theme: tuur29/pages-themes-cayman
show_downloads: true
logo_url: ./image/Fengsim_logo_hi.png
color:
    header: "#000"	
    gradient_left: "#e53935"
    gradient_right: "#f57c00"
    section_title: "#e53935" # this default to gradient_color
syntax_theme: https://stylishthemes.github.io/Syntax-Themes/pygments/css-github/pygments-monokai.css
exclude:
  - toolkit
  - starter
  - framework
  - cli
  - docs