show_downloads: true
remote_theme: tuur29/pages-themes-cayman
color:
  header: "#000000"
  gradient_left: "#ffff00"
  gradient_right: "#ff0000"
  section_title: "#000000"
exclude:
  - toolkit
  - starter
  - framework
  - cli
  - docs