show_downloads: true
remote_theme: tuur29/pages-themes-cayman
color:
  header: "#000000"
  gradient_left: "#FF0000"
  gradient_right: "#000000"
  section_title: "#000000"
exclude:
  - toolkit
  - starter
  - framework
  - cli
  - docs