show_downloads: true
remote_theme: tuur29/pages-themes-cayman
color:
  header: "#000000"
  gradient_left: "#ff8900"
  gradient_right: "#ff3100"
  section_title: "#000000"
syntax_theme: https://stylishthemes.github.io/Syntax-Themes/pygments/css-github/pygments-monokai.css
exclude:
  - toolkit
  - starter
  - framework
  - cli
  - docs