show_downloads: true
remote_theme: tuur29/pages-themes-cayman
color:
  header: "#ffffff"
  gradient_left: "#bdc3c7"
  gradient_right: "#2c3e50"
  section_title: "#000000"
  link: "#ff3100"
exclude:
  - toolkit
  - starter
  - framework
  - cli
  - docs