remote_theme: tuur29/pages-themes-cayman
show_downloads: true
color:
  header: "#ffffff"
  gradient_left: "#00C1D0"
  gradient_right: "#0A0F44"
logo_url: https://github.com/OpenDigitalTwin-Dev/FENGSim/blob/main/image/Fengsim_logo_hi.png	
exclude:
  - toolkit
  - starter
  - framework
  - cli
  - docs