remote_theme: tuur29/pages-themes-cayman
show_downloads: true
color:
    header: "#000"	
    gradient_left: "#0f48a1"
    gradient_right: "#6cc1ba"
    section_title: "#0f48a1" # this default to gradient_color
logo_url: https://github.com/OpenDigitalTwin-Dev/FENGSim/blob/main/image/Fengsim_logo_hi.png	
exclude:
  - toolkit
  - starter
  - framework
  - cli
  - docs