show_downloads: true
remote_theme: tuur29/pages-themes-cayman
color:
  header: "#000000"
  gradient_left: "#8e9eab"
  gradient_right: "#eef2f3"
  section_title: "#000000"
  link: "#ff3100"
exclude:
  - toolkit
  - starter
  - framework
  - cli
  - docs